### ISSUE TITLE
PEP517

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [leapfrogonline/rstr#23]
Could you move the buildsystem to [PEP517](https://peps.python.org/pep-0517/)?

**Comment by bjmc** [comment]
Probably yes. Can you open an PR? Or is there an example I can follow?

**Comment by bjmc** [comment]
Does https://github.com/leapfrogonline/rstr/pull/24 address this issue, or not?

**Comment by Alessandro-Barbieri** [comment]
yes
