### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by gg-mmill** [leapfrogonline/rstr#32]
Hello,
would you agree to make a release with the latest fix commit ?

Thanks a bunch :pray:

**Comment by bjmc** [comment]
Yeah, I'll do a release this week.

**Comment by gg-mmill** [comment]
Thanks,  I spent a few hours because of that typing issue - it only happens for python 3.11.something, because of a change in `random.shuffle`   ( Deprecated since version 3.9, removed in version 3.11: The optional parameter random )

**Comment by bjmc** [comment]
[Done](https://pypi.org/project/rstr/3.2.2/)
