### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sblondon** [leapfrogonline/rstr#5]
Hello,

could you release a 2.3 version on pypi.org?
The current pypi version was released in [2017](https://pypi.org/project/rstr/#history) so the latest fixes and improvement are not provided.

**Comment by bjmc** [comment]
Hello! Certainly we could do another release. To be honest, there have not been a great deal of changes since 2017. IIRC, there's a couple small bugfixes and tests for Python 3.8. If you wanted to do a PR for #4 we could include that in the next release?

**Comment by sblondon** [comment]
My main motivation for a new release is to get `rstr.nonambigous()` function.

I wrote the PR for #4: https://github.com/leapfrogonline/rstr/pull/7

**Comment by bjmc** [comment]
I merged #7. I'm fairly busy right now but I'll try to bundle up a PyPI release this weekend.

**Comment by bjmc** [comment]
Also, thanks for your contributions @sblondon  Would you like to add yourself to the AUTHORS file?

**Comment by sblondon** [comment]
I'm already in the [AUTHORS file](https://github.com/leapfrogonline/rstr/blob/faed3736aa91c8c8b20010946644c71327c3a608/AUTHORS#L8) (with the add of `rstr.nonambigous()`). :-)

**Comment by bjmc** [comment]
Version 2.3.0 is now up on PyPI. I tested it works on Py3.8/Ubuntu 20.04.

**Comment by bjmc** [comment]
Actually, I changed my mind: It's version `3.0.0` because the changes dropping support for Python 2.7 are breaking for anyone still using Py2.
