### ISSUE TITLE
Deletable test?

### ISSUE THREAD

**Issue by sblondon** [leapfrogonline/rstr#8]
The class [TestSystemRandom](https://github.com/leapfrogonline/rstr/blob/51dc76350e394f93dbf00f87e4a3c58ed6c8a924/rstr/tests/test_rstr.py#L50) has only a `setUp()` method. I wonder about the goal of this test.

I have two hypotheses:
 - there were test methods, then deleted so the class can be safely removed
 - the goal is to check `random.SystemRandom()` passed as parameter. In such case, it would be better to rename the method (and add an assertion?).

What do you think about it?

**Comment by bjmc** [comment]
It inherits from `TestRstr` so it runs all the exact same tests, but using `SystemRandom()` rather than the default mersenne twister `random()`

**Comment by sblondon** [comment]
Ok, I missed that.
